net: openthread: Use different kconfig switch for shim and src
MarekPorwisz/zephyr pull request #6
Opened 2020-07-06 11:20 UTC by MarekPorwisz

Different switch was used for build to allow including all shim body
in zephyr without the need for building openthread from this repo. This
allows developer to include custom OpenThread sources as part of the
application.
This change is needed as Thread is a subject of certification and
sources provided by zephyr may not necesairly pass certification or be
precertified. User is allowed to use certified OpenThread version
this way.

Signed-off-by: Marek Porwisz <marek.porwisz@nordicsemi.no>

2020-07-07 07:51 UTC, lmaciejonczyk requested changes

2020-07-07 07:51 UTC, lmaciejonczyk commented on subsys/net/l2/openthread/Kconfig
> +	  while still including open thread shim layer and its depencencies.
Stay consistent: "OpenThread" not "open thread"

2020-07-07 08:29 UTC, lmaciejonczyk approved these changes

2020-07-13 13:42 UTC, rlubos reviewed
While this approach should work, I'd consider using `choice` option here which IMO is more flexible for this use case, in a similar way as Bluetooth does:
https://github.com/zephyrproject-rtos/zephyr/blob/master/subsys/bluetooth/controller/Kconfig#L70

An additional `choice` option can be easily added in NCS:
https://github.com/nrfconnect/sdk-nrfxlib/blob/master/ble_controller/Kconfig#L26

Since there is no way (to my knowledge) to deselect an option that defaults to `y` globally, current approach would require to add `OPENTHREAD_BUILD_SOURCES=n` in each project that wants use pre-compiled OpenThread. With `choice`, the default option could be easily switched for whatever we want to use in NCS.

I don't know what the final goal is (to use the precompiled libraries by default in NCS or not) so up to you to decide.

2020-07-14 10:05 UTC, closed without merging